Repository gordonwatts/snowmass-chat, pull requests merged in 2024-03, with the labels that each got.

#38 Updates with the most recent runnings
  README.md
  snowmass/snowmass-v1.0-update.yaml
Labels: enhancement

#21 Add responses from UIUC GPT-4 chat
  snowmass/uiuc.yaml
Labels: enhancement

#39 Enable other chat models
  README.md
  chathelper/cli.py
  chathelper/model.py
  snowmass/snowmass-v1.0-gtp4-turbo.yaml
Labels: enhancement

#40 "Enable top_k setting"
  README.md
  chathelper/cli.py
Labels: enhancement

#41 Fix issue with PDFs not being downloaded to cache directory
  chathelper/cache.py
Labels: bug

#42 Improve Document Splitting
  .gitignore
  chathelper/cli.py
  chathelper/model.py
  snowmass/snowmass-v1.0-split1000.yaml
Labels: bug, enhancement

#44 Add ability to use different tokenizer models
  chathelper/cli.py
  chathelper/model.py
  snowmass/snowmass-v1.0-large-embedding-gpt4-7.yaml
  snowmass/snowmass-v1.0-large-embedding.yaml
Labels: enhancement

#46 Generate the ACAT Comparison File
  snowmass/snowmass-compare.md
  snowmass/snowmass-v1.0-gtp4-turbo.yaml
  snowmass/snowmass-v1.0-n10.yaml
  snowmass/snowmass-v1.0-split1000.yaml
  snowmass/snowmass-v1.0-update.yaml
  snowmass/snowmass-v1.0.yaml
  snowmass/uiuc.yaml
Labels: enhancement
